import { TimelineObject } from '../types/timeline';

export const PROJECTS: TimelineObject[] = [
  {
    title: 'Porfolio V2',
    subTitle: 'Vite + TypeScript + React',
    timeRange: 'January 2024',
    image: 'icon.ico',
    githubLink: 'https://github.com/guuslammers/portfolio',
    githubPagesLink: 'https://guuslammers.github.io/portfolio/about',
    content: {},
  },
  {
    title: 'Evolutionary Algorithm Visualizer',
    subTitle: 'Java + Swing',
    timeRange: 'October 2022',
    image: 'evolution.png',
    githubLink: 'https://github.com/GuusLammers/Evolutionary-Algorithm-Visualizer',
    content: {},
  },
  {
    title: 'Porfolio V1',
    subTitle: 'Vite + React + Three.js',
    timeRange: 'September 2022',
    image: 'icon.ico',
    githubLink: 'https://github.com/GuusLammers/My-Portfolio-Website',
    githubPagesLink: 'https://guuslammers.github.io/My-Portfolio-Website/',
    content: {},
  },
  {
    title: '2048',
    subTitle: 'Java + Swing',
    timeRange: 'September 2022',
    image: '2048.png',
    githubLink: 'https://github.com/GuusLammers/2048',
    content: {},
  },
  {
    title: 'Sorting Algorithm Visualizer',
    subTitle: 'Python + Tkinter',
    timeRange: 'April 2022',
    image: 'sort.png',
    githubLink: 'https://github.com/GuusLammers/Sorting-Algorithm-Visualizer',
    content: {},
  },
  {
    title: 'Snake',
    subTitle: 'Java + Swing',
    timeRange: 'April 2022',
    image: 'snake.png',
    githubLink: 'https://github.com/GuusLammers/Snake',
    content: {},
  },
  {
    title: 'Flappy Bird Clone',
    subTitle: 'Python + Pygame',
    timeRange: 'January 2021',
    image: 'flappy-bird.png',
    githubLink: 'https://github.com/GuusLammers/Flappy-Bird-Clone',
    content: {},
  },
  {
    title: 'Path Finder',
    subTitle: 'Python + Pygame',
    timeRange: 'December 2020',
    image: 'path-finder.png',
    githubLink: 'https://github.com/GuusLammers/Pathfinder',
    content: {},
  },
  {
    title: 'Spiral Sort',
    subTitle: 'Python + Pygame',
    timeRange: 'December 2020',
    image: 'spiral.png',
    githubLink: 'https://github.com/GuusLammers/Spiral-Sort',
    content: {},
  },
  {
    title: 'Cimex',
    subTitle: 'Python + Flask + Vanilla.js',
    timeRange: 'November 2020',
    image: 'bug.png',
    githubLink: 'https://github.com/GuusLammers/BugTracker-Flask-WebApp',
    content: {},
  },
  {
    title: 'Sudoku',
    subTitle: 'Python + Tkinter',
    timeRange: 'October 2020',
    image: 'sudoku.png',
    githubLink: 'https://github.com/GuusLammers/GUI-Sudoku-Solver',
    content: {},
  },
  {
    title: 'Blackjack',
    subTitle: 'Python + Tkinter',
    timeRange: 'October 2020',
    image: 'blackjack.png',
    githubLink: 'https://github.com/GuusLammers/GUI-Blackjack',
    content: {},
  },
];
